// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "CreativeChallenge",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "CreativeChallenge",
            targets: ["AppModule"],
            bundleIdentifier: "com.tiago.santos.CreativeChallenge",
            teamIdentifier: "22MHF556GA",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .checkmark),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .utilities,
            additionalInfoPlistContentFilePath: "ExtraInfo.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")],
)
